set MATLAB=C:\Program Files\Polyspace\R2021a
"%MATLAB%\bin\win64\gmake" -f slrt_ex_osc_nrt.mk  EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 OPTS="-DEXT_MODE -DON_TARGET_WAIT_FOR_START=1 -DTID01EQ=1"
